/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "status-warning": "#E5A83B",
        "surface-elevated": "#171D25",
        "on-tertiary": "#442c00",
        "on-tertiary-fixed": "#281800",
        "on-secondary-fixed": "#002114",
        "text-secondary": "#A7B0BB",
        "on-surface-variant": "#c1c6d4",
        "surface": "#111318",
        "surface-container-high": "#282a2e",
        "primary-fixed-dim": "#a7c8ff",
        "inverse-primary": "#005eb2",
        "on-primary-fixed": "#001b3c",
        "on-secondary-fixed-variant": "#005237",
        "surface-dim": "#111318",
        "surface-tint": "#a7c8ff",
        "secondary-fixed-dim": "#50dea4",
        "tertiary-fixed": "#ffddaf",
        "status-info": "#5B9CF6",
        "tertiary-fixed-dim": "#ffba43",
        "secondary-fixed": "#71fbbf",
        "text-muted": "#68727E",
        "on-error": "#690005",
        "tertiary": "#ffba43",
        "on-secondary": "#003825",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#614000",
        "inverse-surface": "#e2e2e8",
        "border-subtle": "#252C35",
        "surface-container-highest": "#333539",
        "on-surface": "#e2e2e8",
        "on-background": "#e2e2e8",
        "text-primary": "#F3F5F7",
        "outline-variant": "#414752",
        "secondary-container": "#00b17b",
        "border-strong": "#303945",
        "surface-base": "#090B0F",
        "primary-container": "#5b9cf6",
        "background": "#111318",
        "surface-primary": "#0F1318",
        "text-disabled": "#4B5561",
        "on-primary-fixed-variant": "#004788",
        "secondary": "#50dea4",
        "primary-fixed": "#d5e3ff",
        "surface-variant": "#333539",
        "on-primary": "#003061",
        "error-container": "#93000a",
        "surface-container-low": "#1a1c20",
        "primary": "#a7c8ff",
        "error": "#ffb4ab",
        "on-primary-container": "#003365",
        "surface-container-lowest": "#0c0e12",
        "tertiary-container": "#cf8e00",
        "inverse-on-surface": "#2f3035",
        "outline": "#8b919d",
        "surface-container": "#1e2024",
        "status-safe": "#35C991",
        "on-secondary-container": "#003b27",
        "status-critical": "#F05252",
        "surface-bright": "#37393e",
        "surface-secondary": "#131820",
        "on-tertiary-container": "#462e00"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.125rem",
        "md": "0.25rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-xl": "1.5rem",
        "space-md": "0.75rem",
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-lg": "1rem",
        "space-sm": "0.5rem",
        "margin": "1rem",
        "gutter": "0.75rem"
      },
      fontFamily: {
        "headline-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-lg": ["JetBrains Mono", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "code-block": ["JetBrains Mono", "monospace"]
      }
    }
  },
  plugins: [],
}
